# Generated by Django 4.2.1 on 2023-05-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
