# Generated by Django 4.2.1 on 2023-05-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('T_assest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tassest',
            name='isTAssest',
        ),
        migrations.AddField(
            model_name='tassest',
            name='roleNum',
            field=models.IntegerField(default=1),
        ),
    ]
