# Generated by Django 4.2.1 on 2023-06-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0003_doctor_doctorprofile'),
        ('T_assest', '0002_remove_tassest_istassest_tassest_rolenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tassest',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.doctor'),
        ),
    ]
