# Generated by Django 4.2.1 on 2023-05-18 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Subject', '0005_alter_multiplechoiceq_tassest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleNum', models.IntegerField(default=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='Student/profiles_images/USER.jpg', upload_to='Student/profiles_images/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='PaidCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subject.subject')),
            ],
        ),
    ]
