# Generated by Django 4.2.1 on 2023-05-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subject', '0002_assayq_multiplechoiceq_trueorfalseq'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoiceq',
            name='level',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=255),
        ),
        migrations.AddField(
            model_name='trueorfalseq',
            name='degree',
            field=models.FloatField(default=0.0, max_length=5),
        ),
        migrations.AddField(
            model_name='trueorfalseq',
            name='level',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], default='easy', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='multiplechoiceq',
            name='answer',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], default='a', max_length=255),
        ),
        migrations.AlterField(
            model_name='multiplechoiceq',
            name='choiceA',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='multiplechoiceq',
            name='choiceB',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='multiplechoiceq',
            name='choiceC',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='multiplechoiceq',
            name='choiceD',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trueorfalseq',
            name='quistion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
