# Generated by Django 4.2.1 on 2023-05-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('T_assest', '0002_remove_tassest_istassest_tassest_rolenum'),
        ('Subject', '0003_multiplechoiceq_level_trueorfalseq_degree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='multiplechoiceq',
            name='subject',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='Subject.subject'),
        ),
        migrations.AddField(
            model_name='multiplechoiceq',
            name='tAssest',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='T_assest.tassest'),
        ),
        migrations.AddField(
            model_name='trueorfalseq',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Subject.subject'),
        ),
        migrations.AddField(
            model_name='trueorfalseq',
            name='tAssest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='T_assest.tassest'),
        ),
        migrations.CreateModel(
            name='QuizsDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.FloatField(default=0.0, max_length=5)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Subject.quiz')),
            ],
        ),
        migrations.AddField(
            model_name='quiz',
            name='multipleChoiceQ',
            field=models.ManyToManyField(to='Subject.multiplechoiceq'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subject.subject'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='trueOrFalseQ',
            field=models.ManyToManyField(blank=True, to='Subject.trueorfalseq'),
        ),
        migrations.CreateModel(
            name='QuestionsBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multipleChoiceQ', models.ManyToManyField(to='Subject.multiplechoiceq')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subject.subject')),
                ('trueOrFalseQ', models.ManyToManyField(blank=True, to='Subject.trueorfalseq')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField()),
                ('multipleChoiceQ', models.ManyToManyField(to='Subject.multiplechoiceq')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subject.subject')),
                ('trueOrFalseQ', models.ManyToManyField(blank=True, to='Subject.trueorfalseq')),
            ],
        ),
    ]
