# Generated by Django 4.2.1 on 2023-05-18 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('T_assest', '0002_remove_tassest_istassest_tassest_rolenum'),
        ('Subject', '0004_quiz_multiplechoiceq_subject_multiplechoiceq_tassest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoiceq',
            name='tAssest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='T_assest.tassest'),
        ),
    ]
