# Generated by Django 4.2.1 on 2023-05-18 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_delete_paidcourses'),
        ('Subject', '0005_alter_multiplechoiceq_tassest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Subject.subject')),
            ],
        ),
    ]
