# Generated by Django 4.2.1 on 2023-05-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='isDoctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='roleNum',
            field=models.IntegerField(default=0),
        ),
    ]
