# Generated by Django 4.2.1 on 2023-05-16 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
        ('Doctor', '0003_remove_doctor_isdoctor_doctor_rolenum'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Organization.organization'),
        ),
    ]
