# Generated by Django 4.2.1 on 2023-06-13 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('T_assest', '0003_alter_tassest_doctor'),
        ('Organization', '0003_doctor_doctorprofile'),
        ('Subject', '0007_alter_subject_doctor'),
        ('Doctor', '0006_alter_doctor_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.doctor'),
        ),
        migrations.AlterField(
            model_name='material',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.doctor'),
        ),
        migrations.AlterField(
            model_name='research',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.doctor'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
